### ISSUE TITLE
[Bug] Offline training error `torch.AcceleratorError: Caught AcceleratorError in pin memory thread for device 4`

### ISSUE THREAD

**Issue by Wokzy** [sgl-project/SpecForge#217]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/SpecForge/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/root/home/yegor-yershov/eagle_training/SpecForge/scripts/train_eagle3_offline.py", line 564, in <module>
[rank4]:     main()
[rank4]:   File "/root/home/yegor-yershov/eagle_training/SpecForge/scripts/train_eagle3_offline.py", line 386, in main
[rank4]:     for data in progress_bar:
[rank4]:                 ^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 734, in __next__
[rank4]:     data = self._next_data()
[rank4]:            ^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
[rank4]:     return self._process_data(data, worker_id)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
[rank4]:     data.reraise()
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/_utils.py", line 769, in reraise
[rank4]:     raise exception
[rank4]: torch.AcceleratorError: Caught AcceleratorError in pin memory thread for device 4.
[rank4]: Original Traceback (most recent call last):
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 43, in do_one_step
[rank4]:     data = pin_memory(data, device)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 77, in pin_memory
[rank4]:     {k: pin_memory(sample, device) for k, sample in data.items()}
[rank4]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 66, in pin_memory
[rank4]:     return data.pin_memory(device)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^
[rank4]: torch.AcceleratorError: CUDA error: invalid argument
[rank4]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank4]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank4]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Training Epoch 0:   0%|                                                                                                                                                                                              | 0/4161 [00:14<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/home/yegor-yershov/eagle_training/SpecForge/scripts/train_eagle3_offline.py", line 564, in <module>
[rank0]:     main()
[rank0]:   File "/root/home/yegor-yershov/eagle_training/SpecForge/scripts/train_eagle3_offline.py", line 386, in main
[rank0]:     for data in progress_bar:
[rank0]:                 ^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1181, in __iter__
[rank0]:     for obj in iterable:
[rank0]:                ^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 734, in __next__
[rank0]:     data = self._next_data()
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
[rank0]:     return self._process_data(data, worker_id)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/_utils.py", line 769, in reraise
[rank0]:     raise exception
[rank0]: torch.AcceleratorError: Caught AcceleratorError in pin memory thread for device 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 43, in do_one_step
[rank0]:     data = pin_memory(data, device)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 77, in pin_memory
[rank0]:     {k: pin_memory(sample, device) for k, sample in data.items()}
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py", line 66, in pin_memory
[rank0]:     return data.pin_memory(device)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.AcceleratorError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


terminate called without an active exception
terminate called without an active exception
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:150: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  mask |= a_isnan and not b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_helpers.py:152: UserWarning: Logical operators 'and' and 'or' are deprecated for non-scalar tensors; please use '&' or '|' instead
  equal |= a_isnan and b_isnan
UserWarning: Enable tracemalloc to get the object allocation traceback
W0906 16:24:54.073000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13070 closing signal SIGTERM
W0906 16:24:54.074000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13071 closing signal SIGTERM
W0906 16:24:54.087000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13072 closing signal SIGTERM
W0906 16:24:54.115000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13073 closing signal SIGTERM
W0906 16:24:54.123000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13075 closing signal SIGTERM
W0906 16:24:54.135000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13076 closing signal SIGTERM
W0906 16:24:54.178000 13003 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 13077 closing signal SIGTERM
E0906 16:25:15.083000 13003 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: -6) local_rank: 4 (pid: 13074) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

### Reproduction

```
NUM_GPUS=8
torchrun \
    --standalone \
    --nproc_per_node $NUM_GPUS \
    $ROOT_DIR/scripts/train_eagle3_offline.py \
    --target-model-path $MODEL_PATH \
    --train-hidden-states-path $HIDDEN_STATES_DIR \
    --draft-model-config config.json \
    --train-data-path $ROOT_DIR/cache/dataset/$DATASET_FNAME \
    --is-preformatted \
    --build-dataset-num-proc 64 \
    --output-dir $ROOT_DIR/outputs/qwen_235b_offline \
    --num-epochs 1 \
    --draft-global-batch-size 128 \
    --draft-micro-batch-size 16 \
    --learning-rate 5e-5 \
    --max-length 16384 \
    --chat-template qwen \
    --cache-dir $ROOT_DIR/cache \
    --embedding-key model.embed_tokens.weight \
    --tp-size $NUM_GPUS \
```

### Environment

Python: 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H200
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.68
CUDA Driver Version: 570.172.08
PyTorch: 2.8.0+cu126
sglang: 0.5.2rc2
sgl_kernel: 0.3.8
flashinfer_python: 0.3.0
triton: 3.4.0
transformers: 4.56.0
torchao: 0.9.0+cu126
numpy: 2.3.2
aiohttp: 3.12.15
fastapi: 0.116.1
hf_transfer: 0.1.9
huggingface_hub: 0.34.4
interegular: 0.3.3
modelscope: 1.29.2
orjson: 3.11.3
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.7
python-multipart: 0.0.20
pyzmq: 27.0.2
uvicorn: 0.35.0
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.23
openai: 1.99.1
tiktoken: 0.11.0
anthropic: 0.66.0
litellm: Module Not Found
decord: 0.6.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	0-24	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	0-24	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	0-24	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	25-49	1		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	50-74	2		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	50-74	2		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	50-74	2		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	75-99	3		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576

**Comment by Wokzy** [comment]
This is fixed by setting pin_memory=False in train_dataloader:
```
train_dataloader = prepare_dp_dataloaders(
        train_eagle3_dataset,
        args.draft_micro_batch_size,
        num_workers=4,
        shuffle=True,
        process_group=get_dp_group(),
        pin_memory=False,
    )
```
