### ISSUE TITLE
[Bug] Abnormal memory usage and Out-of-Memory in eagle3 training.

### ISSUE THREAD

**Issue by coco-alen** [sgl-project/SpecForge#466]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/SpecForge/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

When training an Eagle model for qwen3, I could only set the batch size to 2; increasing it further caused an OutOfMemoryError (OOM). I was using 4 H200 GPUs, each with 140GB of VRAM. This VRAM usage was clearly abnormal.

I found that most of the OOMs occurred in the `padding` function within `specforge/utils.py`.

### Reproduction

```python
NUM_GPUS=${1:-4}

#torch memory segment
export PYTORCH_ALLOC_CONF=expandable_segments:True
CUDA_VISIBLE_DEVICES=4,5,6,7 \
torchrun \
    --standalone \
    --nproc_per_node $NUM_GPUS \
    $ROOT_DIR/scripts/train_eagle3.py \
    --target-model-path Qwen/Qwen3-8B \
    --draft-model-config $ROOT_DIR/configs/qwen3-8b-eagle3.json \
    --train-data-path $ROOT_DIR/cache/dataset/dflash_dataset_nemotron_800K.jsonl \
    --output-dir $ROOT_DIR/outputs/qwen3-8b-eagle-nemotron \
    --num-epochs 10 \
    --batch-size 2 \
    --learning-rate 2e-4 \
    --max-length 4096 \
    --chat-template qwen \
    --cache-dir $ROOT_DIR/cache \
    --embedding-key model.embed_tokens.weight \
    --log-interval 50 \
    --save-interval 1000 \
    --tp-size $NUM_GPUS \
    --target-model-backend sglang \
    --sglang-attention-backend fa3 \
    --sglang-mem-fraction-static 0.1 \
    --report-to wandb \
    --wandb-project specforge-qwen3-8b-eagle \
    --wandb-name qwen3-8b-eagle-nemotron
```

### Environment

specforge                 0.2.0

**Comment by MLKoz2** [comment]
Any updates here? Did you find a way to decrease VRAM usage?

**Comment by fengyuli-dev** [comment]
I faced similar a issue where I have 8 x h200 and was only able to use batch size = 1 for training. VRAM usage is ~65GB per GPU but increasing batch size to 2 results in OOM.

**Comment by laoconeth** [comment]
Hello, my teammates and I would like to work on this OOM issue. Could you please assign it to me (@laoconeth)?

**Comment by laoconeth** [comment]
@FrankLeeeee @jiapingW

**Comment by jiapingW** [comment]
Sure.

**Comment by jiapingW** [comment]
Is there any progress here, or is there any assistance needed?

**Comment by laoconeth** [comment]
Memory spike is resolved, preparing to create PR.

**Comment by YoavMiron** [comment]
Is this issue solved?

**Comment by laoconeth** [comment]
Opened a PR to address this: #524

**Comment by jiapingW** [comment]
You can try the latest code and set `sglang-mem-fraction-static=0.4`.

**Comment by YoavMiron** [comment]
It is already set to this value, perhaps I'm experiencing a different issue. My problem is when using draft-accumulation-steps>1 - I get OOM even with bs=1, draft-accumulation-steps=2, although I don't get OOM when even with bs=2, draft-accumulation-steps=1.

**Comment by laoconeth** [comment]
@YoavMiron is your issue similar to that described in PR #524 ?
